// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3);
}

export function AddToYouTubeQueue(arg1, arg2) {
  return window['go']['main']['App']['AddToYouTubeQueue'](arg1, arg2);
}

export function CleanupOrphanGroups() {
  return window['go']['main']['App']['CleanupOrphanGroups']();
}

export function ClearTranslationCache() {
  return window['go']['main']['App']['ClearTranslationCache']();
}

export function ClearYouTubeQueue(arg1) {
  return window['go']['main']['App']['ClearYouTubeQueue'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function GetAccounts(arg1) {
  return window['go']['main']['App']['GetAccounts'](arg1);
}

export function GetAccountsForPlatform(arg1) {
  return window['go']['main']['App']['GetAccountsForPlatform'](arg1);
}

export function GetDays(arg1, arg2) {
  return window['go']['main']['App']['GetDays'](arg1, arg2);
}

export function GetGroupAccounts(arg1) {
  return window['go']['main']['App']['GetGroupAccounts'](arg1);
}

export function GetGroupDownloadStatus() {
  return window['go']['main']['App']['GetGroupDownloadStatus']();
}

export function GetGroupOptions() {
  return window['go']['main']['App']['GetGroupOptions']();
}

export function GetGroupRuns(arg1, arg2) {
  return window['go']['main']['App']['GetGroupRuns'](arg1, arg2);
}

export function GetGroupTree() {
  return window['go']['main']['App']['GetGroupTree']();
}

export function GetManualDownloadStatus() {
  return window['go']['main']['App']['GetManualDownloadStatus']();
}

export function GetMedia(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['GetMedia'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function GetMonths(arg1) {
  return window['go']['main']['App']['GetMonths'](arg1);
}

export function GetPopularTags(arg1) {
  return window['go']['main']['App']['GetPopularTags'](arg1);
}

export function GetTranslationCacheStats() {
  return window['go']['main']['App']['GetTranslationCacheStats']();
}

export function GetYears() {
  return window['go']['main']['App']['GetYears']();
}

export function GetYouTubeHashtags() {
  return window['go']['main']['App']['GetYouTubeHashtags']();
}

export function GetYouTubeQueue(arg1) {
  return window['go']['main']['App']['GetYouTubeQueue'](arg1);
}

export function GetYouTubeQueueStats() {
  return window['go']['main']['App']['GetYouTubeQueueStats']();
}

export function GetYouTubeWorkerStatus() {
  return window['go']['main']['App']['GetYouTubeWorkerStatus']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PruneMissingFiles() {
  return window['go']['main']['App']['PruneMissingFiles']();
}

export function ReindexAccount(arg1, arg2) {
  return window['go']['main']['App']['ReindexAccount'](arg1, arg2);
}

export function ReindexDatabase() {
  return window['go']['main']['App']['ReindexDatabase']();
}

export function ReindexIncremental() {
  return window['go']['main']['App']['ReindexIncremental']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RemoveQueueItem(arg1) {
  return window['go']['main']['App']['RemoveQueueItem'](arg1);
}

export function RetryFailedQueue() {
  return window['go']['main']['App']['RetryFailedQueue']();
}

export function SaveVideoThumbnail(arg1, arg2) {
  return window['go']['main']['App']['SaveVideoThumbnail'](arg1, arg2);
}

export function SetYouTubeHashtags(arg1) {
  return window['go']['main']['App']['SetYouTubeHashtags'](arg1);
}

export function StartGroupDownload(arg1, arg2) {
  return window['go']['main']['App']['StartGroupDownload'](arg1, arg2);
}

export function StartManualDownload(arg1) {
  return window['go']['main']['App']['StartManualDownload'](arg1);
}

export function StartYouTubeWorker() {
  return window['go']['main']['App']['StartYouTubeWorker']();
}

export function StopGroupDownload() {
  return window['go']['main']['App']['StopGroupDownload']();
}

export function StopManualDownload() {
  return window['go']['main']['App']['StopManualDownload']();
}

export function StopYouTubeWorker() {
  return window['go']['main']['App']['StopYouTubeWorker']();
}

export function TranslateBatch(arg1, arg2) {
  return window['go']['main']['App']['TranslateBatch'](arg1, arg2);
}

export function TranslateText(arg1, arg2) {
  return window['go']['main']['App']['TranslateText'](arg1, arg2);
}

export function UpdateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3);
}

export function UpdateGroup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3, arg4);
}

export function UpdateQueueItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateQueueItem'](arg1, arg2, arg3, arg4, arg5);
}
