// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:number,arg2:string,arg3:string):Promise<Record<string, any>>;

export function AddToYouTubeQueue(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function CleanupOrphanGroups():Promise<Record<string, any>>;

export function ClearTranslationCache():Promise<void>;

export function ClearYouTubeQueue(arg1:boolean):Promise<number>;

export function CreateGroup(arg1:string,arg2:number):Promise<Record<string, any>>;

export function DeleteGroup(arg1:number):Promise<void>;

export function GetAccounts(arg1:string):Promise<Array<main.AccountWithPlatform>>;

export function GetAccountsForPlatform(arg1:string):Promise<Array<string>>;

export function GetDays(arg1:string,arg2:string):Promise<Array<string>>;

export function GetGroupAccounts(arg1:number):Promise<Array<main.IdolAccount>>;

export function GetGroupDownloadStatus():Promise<Record<string, any>>;

export function GetGroupOptions():Promise<Array<main.GroupOption>>;

export function GetGroupRuns(arg1:number,arg2:number):Promise<Array<main.IdolRun>>;

export function GetGroupTree():Promise<Array<main.GroupNode>>;

export function GetManualDownloadStatus():Promise<Record<string, any>>;

export function GetMedia(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:number,arg12:number):Promise<main.FilterResult>;

export function GetMonths(arg1:string):Promise<Array<string>>;

export function GetPopularTags(arg1:number):Promise<Array<main.TagWithCount>>;

export function GetTranslationCacheStats():Promise<Record<string, any>>;

export function GetYears():Promise<Array<string>>;

export function GetYouTubeQueue(arg1:string):Promise<Array<main.QueueItem>>;

export function GetYouTubeQueueStats():Promise<main.QueueStats>;

export function GetYouTubeWorkerStatus():Promise<Record<string, any>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PruneMissingFiles():Promise<Record<string, any>>;

export function ReindexAccount(arg1:string,arg2:string):Promise<main.ReindexResult>;

export function ReindexDatabase():Promise<main.ReindexResult>;

export function ReindexIncremental():Promise<main.ReindexResult>;

export function RemoveAccount(arg1:number):Promise<void>;

export function RemoveQueueItem(arg1:number):Promise<void>;

export function RetryFailedQueue():Promise<number>;

export function SaveVideoThumbnail(arg1:string,arg2:string):Promise<string>;

export function StartGroupDownload(arg1:number,arg2:Array<string>):Promise<Record<string, any>>;

export function StartManualDownload(arg1:main.ManualDownloadConfig):Promise<Record<string, any>>;

export function StartYouTubeWorker():Promise<Record<string, any>>;

export function StopGroupDownload():Promise<Record<string, any>>;

export function StopManualDownload():Promise<Record<string, any>>;

export function StopYouTubeWorker():Promise<Record<string, any>>;

export function TranslateBatch(arg1:Array<string>,arg2:string):Promise<Record<string, string>>;

export function TranslateText(arg1:string,arg2:string):Promise<string>;

export function UpdateAccount(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function UpdateGroup(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateQueueItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
